services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15-alpine
    container_name: medtest-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sql_migration_study
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./pg_migration_study.sql:/docker-entrypoint-initdb.d/01-init.sql
    networks:
      - postgres_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d sql_migration_study"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local

networks:
  postgres_network:
    driver: bridge