version: '3.8'

services:
  # PostgreSQL база данных
  postgres:
    image: postgres:15
    container_name: fastapi_postgres
    environment:
      POSTGRES_DB: fastapi_db
      POSTGRES_USER: fastapi_user
      POSTGRES_PASSWORD: fastapi_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fastapi_network
    restart: unless-stopped

  # FastAPI приложение
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://fastapi_user:fastapi_password@postgres:5432/fastapi_db
      ENVIRONMENT: development
    depends_on:
      - postgres
    networks:
      - fastapi_network
    restart: unless-stopped
    volumes:
      - .:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

  # pgAdmin для управления БД (опционально)
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: fastapi_pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@admin.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres
  #   networks:
  #     - fastapi_network
  #   restart: unless-stopped

volumes:
  postgres_data:

networks:
  fastapi_network:
    driver: bridge
